---
- name: Working with docker container on prod server
  hosts: prod
  become: yes

  tasks:

#  - name: Stop a container
#    docker_container:
#     name: myapp
#     state: stopped
#
#  - name: Remove container
#    docker_container:
#     name: myapp
#     state: absent
#
  - name: Start new container
    docker_container:
      name: myapp
      image: "igoren007/my_app1:latest"
      state: started
      published_ports:
        - 0.0.0.0:80:80
    