---
- name: Working with docker container on prod server
  hosts: prod
  become: yes

  tasks:

  - name: Stop container
    shell: docker stop myapp || true && docker rm myapp || true

  - name: Remove old image
    shell: docker rmi igoren007/my_app1 || true

  - name: Start new container
    docker_container:
      name: myapp
      image: "igoren007/my_app1:{{ tag_id }}"
      state: started
      published_ports:
        - 0.0.0.0:80:80
    